export const timezones = [
  // México
  { value: 'America/Mexico_City', label: 'México (CDMX)', flag: '🇲🇽' },
  { value: 'America/Cancun', label: 'México (Cancún)', flag: '🇲🇽' },
  { value: 'America/Monterrey', label: 'México (Monterrey)', flag: '🇲🇽' },
  { value: 'America/Hermosillo', label: 'México (Hermosillo)', flag: '🇲🇽' },
  { value: 'America/Tijuana', label: 'México (Tijuana)', flag: '🇲🇽' },
  { value: 'America/Mazatlan', label: 'México (Mazatlán)', flag: '🇲🇽' },
  // LATAM
  { value: 'America/Guatemala', label: 'Guatemala', flag: '🇬🇹' },
  { value: 'America/Belize', label: 'Belice', flag: '🇧🇿' },
  { value: 'America/El_Salvador', label: 'El Salvador', flag: '🇸🇻' },
  { value: 'America/Tegucigalpa', label: 'Honduras', flag: '🇭🇳' },
  { value: 'America/Managua', label: 'Nicaragua', flag: '🇳🇮' },
  { value: 'America/Costa_Rica', label: 'Costa Rica', flag: '🇨🇷' },
  { value: 'America/Panama', label: 'Panamá', flag: '🇵🇦' },
  { value: 'America/Bogota', label: 'Colombia', flag: '🇨🇴' },
  { value: 'America/Lima', label: 'Perú', flag: '🇵🇪' },
  { value: 'America/Caracas', label: 'Venezuela', flag: '🇻🇪' },
  { value: 'America/La_Paz', label: 'Bolivia', flag: '🇧🇴' },
  { value: 'America/Santiago', label: 'Chile', flag: '🇨🇱' },
  { value: 'America/Asuncion', label: 'Paraguay', flag: '🇵🇾' },
  { value: 'America/Montevideo', label: 'Uruguay', flag: '🇺🇾' },
  {
    value: 'America/Argentina/Buenos_Aires',
    label: 'Argentina (Buenos Aires)',
    flag: '🇦🇷',
  },
  {
    value: 'America/Argentina/Cordoba',
    label: 'Argentina (Córdoba)',
    flag: '🇦🇷',
  },
  { value: 'America/Argentina/Salta', label: 'Argentina (Salta)', flag: '🇦🇷' },
  { value: 'America/Sao_Paulo', label: 'Brasil (São Paulo)', flag: '🇧🇷' },
  { value: 'America/Manaus', label: 'Brasil (Manaus)', flag: '🇧🇷' },
  { value: 'America/Fortaleza', label: 'Brasil (Fortaleza)', flag: '🇧🇷' },
  // Otros
  { value: 'America/New_York', label: 'Nueva York', flag: '🇺🇸' },
  { value: 'America/Los_Angeles', label: 'Los Ángeles', flag: '🇺🇸' },
  { value: 'Europe/London', label: 'Londres', flag: '🇬🇧' },
  { value: 'Europe/Paris', label: 'París', flag: '🇫🇷' },
  { value: 'Europe/Madrid', label: 'Madrid', flag: '🇪🇸' },
  { value: 'Asia/Tokyo', label: 'Tokio', flag: '🇯🇵' },
  { value: 'Asia/Shanghai', label: 'Shanghái', flag: '🇨🇳' },
  { value: 'Australia/Sydney', label: 'Sídney', flag: '🇦🇺' },
];
